### ISSUE TITLE
Segfault when searching in an empty buffer

### ISSUE THREAD

**Issue by Pyrohh** [martanne/vis#137]
How to reproduce:
```
$ ./vis
<search for anything, backwards or forwards>
<SIGSEGV>
```

Here's a diff which avoids the problem, although it might not be ideal:

```diff
diff --git a/text-regex.c b/text-regex.c
index cff8587..beda175 100644
--- a/text-regex.c
+++ b/text-regex.c
@@ -36,6 +36,8 @@ int text_search_range_forward(Text *txt, size_t pos, size_t len, Regex *r, size_
 	if (!buf)
 		return REG_NOMATCH;
 	len = text_bytes_get(txt, pos, len, buf);
+	if (len == 0)
+		return REG_NOMATCH;
 	buf[len] = '\0';
 	regmatch_t match[nmatch];
 	int ret = regexec(&r->regex, buf, nmatch, match, eflags);
@@ -54,6 +56,8 @@ int text_search_range_backward(Text *txt, size_t pos, size_t len, Regex *r, size
 	if (!buf)
 		return REG_NOMATCH;
 	len = text_bytes_get(txt, pos, len, buf);
+	if (len == 0)
+		return REG_NOMATCH;
 	buf[len] = '\0';
 	regmatch_t match[nmatch];
 	char *cur = buf;

```

And the full GDB log w/ some annotations:

```
Starting program: /home/michael/src/vis/vis 
Reading symbols from /home/michael/src/vis/vis...done.
Reading symbols from /usr/local/lib/liblua5.2.so.5.2...done.
Reading symbols from /usr/lib/libm.so.9.0...done.
Reading symbols from /usr/local/lib/libtermkey.so.0.0...done.
Reading symbols from /usr/lib/libncursesw.so.14.0...done.
Reading symbols from /usr/lib/libc.so.84.2...done.
Reading symbols from /usr/libexec/ld.so...done.
Reading in symbols for /usr/src/libexec/ld.so/resolve.c...done.
Reading in symbols for /usr/src/libexec/ld.so/loader.c...done.
Reading in symbols for /usr/src/libexec/ld.so/dlfcn.c...done.
Reading symbols from /usr/local/lib/lua/5.2/lpeg.so...done.
Reading in symbols for text-regex.c...done.






Program received signal SIGSEGV, Segmentation fault.
0x00000292dc012fd2 in text_search_range_forward (txt=Reading in symbols for text.c...done.
0x29501e2c000, pos=1, len=0, r=0x295aa022fc0, nmatch=1, pmatch=0x7f7fffff5550, eflags=0) at text-regex.c:39
39		buf[len] = '\0';
Reading in symbols for text-motions.c...done.
Reading in symbols for vis-motions.c...done.
Reading in symbols for vis.c...done.
Reading in symbols for main.c...done.






bt:
#0  0x00000292dc012fd2 in text_search_range_forward (txt=0x29501e2c000, pos=1, len=0, r=0x295aa022fc0, nmatch=1, pmatch=0x7f7fffff5550, eflags=0) at text-regex.c:39
#1  0x00000292dc0115b9 in text_search_forward (txt=0x29501e2c000, pos=0, regex=0x295aa022fc0) at text-motions.c:622
#2  0x00000292dc02435a in search_forward (vis=0x29519101000, txt=0x29501e2c000, pos=0) at vis-motions.c:41
#3  0x00000292dc026e11 in action_do (vis=0x29519101000, a=0x295191016c8) at vis.c:513
#4  0x00000292dc029051 in vis_motion (vis=0x29519101000, motion=VIS_MOVE_SEARCH_NEXT) at vis.c:1074
#5  0x00000292dc0275fd in prompt_cmd (vis=0x29519101000, type=47 '/', cmd=0x295090fe1a0 "aaaaaaaaa") at vis.c:639
#6  0x00000292dc0298e4 in vis_prompt_enter (vis=0x29519101000) at vis.c:1268
#7  0x00000292dc00ddab in call (vis=0x29519101000, keys=0x295be6aa807 "", arg=0x292dc435898) at main.c:1564
#8  0x00000292dc027ab3 in vis_keys_raw (vis=0x29519101000, buf=0x295191016a8, input=0x294dd61e2f0 "<Enter>") at vis.c:710
#9  0x00000292dc027e18 in vis_keys_push (vis=0x29519101000, input=0x294dd61e2f0 "<Enter>") at vis.c:777
#10 0x00000292dc02871a in vis_run (vis=0x29519101000, argc=1, argv=0x7f7fffff5b98) at vis.c:920
#11 0x00000292dc00e48a in main (argc=1, argv=0x7f7fffff5b98) at main.c:1690






bt full:
#0  0x00000292dc012fd2 in text_search_range_forward (txt=0x29501e2c000, pos=1, len=0, r=0x295aa022fc0, nmatch=1, pmatch=0x7f7fffff5550, eflags=0) at text-regex.c:39
	buf = 0x295572ce280 <Address 0x295572ce280 out of bounds>
	match = 0x0
	ret = 0
#1  0x00000292dc0115b9 in text_search_forward (txt=0x29501e2c000, pos=0, regex=0x295aa022fc0) at text-motions.c:622
	start = 1
	end = 0
	match = {{start = 210455756800, end = 0}}
	found = false
#2  0x00000292dc02435a in search_forward (vis=0x29519101000, txt=0x29501e2c000, pos=0) at vis-motions.c:41
No locals.
#3  0x00000292dc026e11 in action_do (vis=0x29519101000, a=0x295191016c8) at vis.c:513
	i = 0
	start = 0
	pos = 0
	reg = (Register *) 0x29519101360
	c = {count = 1, reg = 0x29519101360, range = {start = 18446744073709551615, end = 18446744073709551615}, pos = 0, newpos = 18446744073709551615, linewise = false, arg = 0x29519101700}
	cursor = (Cursor *) Reading in symbols for view.c...done.
0x2957a2b3200
	next = (Cursor *) 0x0
	win = (Win *) 0x295a2c20880
	txt = (Text *) 0x29501e2c000
	view = (View *) 0x295777f0c00
	repeatable = false
	multiple_cursors = false
	linewise = false
#4  0x00000292dc029051 in vis_motion (vis=0x29519101000, motion=VIS_MOVE_SEARCH_NEXT) at vis.c:1074
	ap = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7f7fffff5810, reg_save_area = 0x7f7fffff5750}}
#5  0x00000292dc0275fd in prompt_cmd (vis=0x29519101000, type=47 '/', cmd=0x295090fe1a0 "aaaaaaaaa") at vis.c:639
No locals.
#6  0x00000292dc0298e4 in vis_prompt_enter (vis=0x29519101000) at vis.c:1268
	s = 0x295090fe1a0 "aaaaaaaaa"
#7  0x00000292dc00ddab in call (vis=0x29519101000, keys=0x295be6aa807 "", arg=0x292dc435898) at main.c:1564
No locals.
#8  0x00000292dc027ab3 in vis_keys_raw (vis=0x29519101000, buf=0x295191016a8, input=0x294dd61e2f0 "<Enter>") at vis.c:710
	tmp = 0 '\0'
	keys = 0x295be6aa800 "<Enter>"
	start = 0x295be6aa800 "<Enter>"
	cur = 0x295be6aa800 "<Enter>"
	end = 0x295be6aa807 ""
	prefix = false
	binding = (KeyBinding *) 0x292dc437710
#9  0x00000292dc027e18 in vis_keys_push (vis=0x29519101000, input=0x294dd61e2f0 "<Enter>") at vis.c:777
No locals.
#10 0x00000292dc02871a in vis_run (vis=0x29519101000, argc=1, argv=0x7f7fffff5b98) at vis.c:920
	fds = {fds_bits = {1, 0 <repeats 31 times>}}
	r = 1
	termkey = (TermKey *) 0x295b073d400
	key = 0x294dd61e2f0 "<Enter>"
	idle = {tv_sec = 0, tv_nsec = 0}
	timeout = (struct timespec *) 0x0
	emptyset = 0
#11 0x00000292dc00e48a in main (argc=1, argv=0x7f7fffff5b98) at main.c:1690
	event = {vis_start = 0x292dc023026Reading in symbols for vis-lua.c...done.
 <vis_lua_start>, vis_quit = 0x292dc0233e2 <vis_lua_quit>, file_open = 0x292dc023464 <vis_lua_file_open>, file_save = 0x292dc023472 <vis_lua_file_save>, file_close = 0x292dc023480 <vis_lua_file_close>, 
  win_open = 0x292dc023527 <vis_lua_win_open>, win_close = 0x292dc0235b1 <vis_lua_win_close>}
	sa = {__sigaction_u = {__sa_handler = 0x292dc00e23d <signal_handler>, __sa_sigaction = 0x292dc00e23d <signal_handler>}, sa_mask = 0, sa_flags = 64}
	blockset = 134217728
	status = 0
```

**Comment by martanne** [comment]
Thanks for the detailed report! Did the last few patches fix the issue?

**Comment by Pyrohh** [comment]
> Did the last few patches fix the issue?

Yes, thanks for the quick response. I'm glad you added a new function given the duplication :D
