### ISSUE TITLE
Multiple segfaults from Lua configuration

### ISSUE THREAD

**Issue by p-e-w** [martanne/vis#561]
*Latest vis master on Fedora 25.*

Putting this in my `visrc.lua`

```lua
require("vis")
vis:feedkeys(" ")
```

`vis` segfaults on startup. Compiling with `make debug` and installing all relevant debug symbols I was able to obtain the following backtrace using `gdb`:

```
#0  0x0000555555584d2b in ?? ()
#1  0x0000555555592e51 in ?? ()
#2  0x000055555556474a in ?? ()
#3  0x000055555558676a in ?? ()
#4  0x0000555555586b6e in ?? ()
#5  0x0000555555587814 in ?? ()
#6  0x0000555555586a88 in ?? ()
#7  0x000055555558c7f2 in ?? ()
#8  0x00007ffff7540310 in luaD_precall (L=L@entry=0x5555557df048, 
    func=func@entry=0x555555860d70, nresults=nresults@entry=0) at ldo.c:434
#9  0x00007ffff7555ee5 in luaV_execute (L=L@entry=0x5555557df048) at lvm.c:1134
#10 0x00007ffff75405ef in luaD_call (L=L@entry=0x5555557df048, 
    func=<optimized out>, nResults=nResults@entry=1) at ldo.c:499
#11 0x00007ffff7540641 in luaD_callnoyield (L=L@entry=0x5555557df048, 
    func=<optimized out>, nResults=nResults@entry=1) at ldo.c:509
#12 0x00007ffff753703c in lua_callk (L=L@entry=0x5555557df048, 
    nargs=nargs@entry=2, nresults=nresults@entry=1, ctx=ctx@entry=0, 
    k=k@entry=0x0) at lapi.c:924
#13 0x00007ffff75471ec in ll_require (L=0x5555557df048) at loadlib.c:609
#14 0x00007ffff7540310 in luaD_precall (L=L@entry=0x5555557df048, 
    func=0x5555557e7410, nresults=0) at ldo.c:434
#15 0x00007ffff75405e3 in luaD_call (L=L@entry=0x5555557df048, 
    func=<optimized out>, nResults=<optimized out>) at ldo.c:498
#16 0x00007ffff7540641 in luaD_callnoyield (L=0x5555557df048, 
    func=<optimized out>, nResults=<optimized out>) at ldo.c:509
#17 0x00007ffff753fa22 in luaD_rawrunprotected (L=L@entry=0x5555557df048, 
    f=f@entry=0x7ffff7535af0 <f_call>, ud=ud@entry=0x7fffffffb930) at ldo.c:142
#18 0x00007ffff754095d in luaD_pcall (L=L@entry=0x5555557df048, 
    func=func@entry=0x7ffff7535af0 <f_call>, u=u@entry=0x7fffffffb930, 
    old_top=240, ef=<optimized out>) at ldo.c:729
#19 0x00007ffff7537111 in lua_pcallk (L=0x5555557df048, nargs=1, nresults=0, 
    errfunc=<optimized out>, ctx=0, k=0x0) at lapi.c:968
#20 0x000055555558a012 in ?? ()
#21 0x000055555558fc33 in ?? ()
#22 0x00005555555819c4 in ?? ()
#23 0x00005555555823c4 in ?? ()
#24 0x0000555555583cb1 in ?? ()
#25 0x000055555556662c in ?? ()
#26 0x00007ffff6c7b401 in __libc_start_main (main=0x555555565bf9, argc=1, 
    argv=0x7fffffffdfc8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdfb8)
    at ../csu/libc-start.c:289
#27 0x000055555556140a in ?? ()
```

---

A similar segfault occurs when the contents of `visrc.lua` are

```lua
require("vis")
vis.mode = vis.modes.VISUAL
```

I'm not able to tell from the documentation whether `vis.mode` is intended to be read-only, but even if it were it shouldn't be possible to crash the editor from Lua.

The backtrace in this case is

```
#0  0x0000555555591331 in ?? ()
#1  0x0000555555590b35 in ?? ()
#2  0x0000555555590b9b in ?? ()
#3  0x000055555558cdd7 in ?? ()
#4  0x00007ffff7540310 in luaD_precall (L=L@entry=0x5555557df048, 
    func=0x555555860c10, nresults=0) at ldo.c:434
#5  0x00007ffff75405e3 in luaD_call (L=L@entry=0x5555557df048, 
    func=<optimized out>, nResults=nResults@entry=0) at ldo.c:498
#6  0x00007ffff755341c in luaT_callTM (L=L@entry=0x5555557df048, 
    f=<optimized out>, p1=<optimized out>, 
    p2=p2@entry=0x7ffff75405e3 <luaD_call+35>, p3=0x555555860c00, 
    p3@entry=0x7ffff755b5d4, hasres=hasres@entry=0) at ltm.c:114
#7  0x00007ffff7554e9d in luaV_finishset (L=L@entry=0x5555557df048, 
    t=<optimized out>, t@entry=0x555555860bf0, 
    key=0x7ffff75405e3 <luaD_call+35>, val=0x7ffff755b5d4, 
    slot=<optimized out>) at lvm.c:229
#8  0x00007ffff755671b in luaV_execute (L=L@entry=0x5555557df048) at lvm.c:864
#9  0x00007ffff75405ef in luaD_call (L=L@entry=0x5555557df048, 
    func=<optimized out>, nResults=nResults@entry=1) at ldo.c:499
#10 0x00007ffff7540641 in luaD_callnoyield (L=L@entry=0x5555557df048, 
    func=<optimized out>, nResults=nResults@entry=1) at ldo.c:509
#11 0x00007ffff753703c in lua_callk (L=L@entry=0x5555557df048, 
    nargs=nargs@entry=2, nresults=nresults@entry=1, ctx=ctx@entry=0, 
    k=k@entry=0x0) at lapi.c:924
#12 0x00007ffff75471ec in ll_require (L=0x5555557df048) at loadlib.c:609
#13 0x00007ffff7540310 in luaD_precall (L=L@entry=0x5555557df048, 
    func=0x5555557e7410, nresults=0) at ldo.c:434
#14 0x00007ffff75405e3 in luaD_call (L=L@entry=0x5555557df048, 
    func=<optimized out>, nResults=<optimized out>) at ldo.c:498
#15 0x00007ffff7540641 in luaD_callnoyield (L=0x5555557df048, 
    func=<optimized out>, nResults=<optimized out>) at ldo.c:509
#16 0x00007ffff753fa22 in luaD_rawrunprotected (L=L@entry=0x5555557df048, 
    f=f@entry=0x7ffff7535af0 <f_call>, ud=ud@entry=0x7fffffffb930) at ldo.c:142
#17 0x00007ffff754095d in luaD_pcall (L=L@entry=0x5555557df048, 
    func=func@entry=0x7ffff7535af0 <f_call>, u=u@entry=0x7fffffffb930, 
    old_top=240, ef=<optimized out>) at ldo.c:729
#18 0x00007ffff7537111 in lua_pcallk (L=0x5555557df048, nargs=1, nresults=0, 
    errfunc=<optimized out>, ctx=0, k=0x0) at lapi.c:968
#19 0x000055555558a012 in ?? ()
#20 0x000055555558fc33 in ?? ()
#21 0x00005555555819c4 in ?? ()
#22 0x00005555555823c4 in ?? ()
#23 0x0000555555583cb1 in ?? ()
#24 0x000055555556662c in ?? ()
#25 0x00007ffff6c7b401 in __libc_start_main (main=0x555555565bf9, argc=1, 
    argv=0x7fffffffdfc8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdfb8)
    at ../csu/libc-start.c:289
#26 0x000055555556140a in ?? ()
```

**Comment by martanne** [comment]
Hi, can you provide a bit more context on what you want to achieve?

Currently there are a lot of places where vis assumes that there exists at least one window. However, this is not the case when the configuration file is sourced. A lot of things simply can not be done at this stage. 

I agree that we shouldn't crash though. But adding lots of

```
if (!vis->win)
    return;
```

isn't not really appealing either.

**Comment by p-e-w** [comment]
> Hi, can you provide a bit more context on what you want to achieve?

My overall goal is to port [Envy](https://github.com/p-e-w/envy) to Vis. This issue is just a bug I randomly stumbled across while experimenting.

Envy works quite differently from vim so trying to make Vis behave like Envy will likely uncover lots of edge cases in the plugin API. The idea is to use visual mode as "Envy mode" (because that's the only mode in Vis that supports selections) and shift back and forth to normal mode as required to do things like regular (non-selection) cursor movement. The initial experiments worked quite well so I'm optimistic most of Envy's functionality can be transferred to Vis.

> I agree that we shouldn't crash though. But adding lots of
>
> if (!vis->win)
>    return;
>
> isn't not really appealing either.

I appreciate that you don't want to riddle the code with such boilerplate, but is there really an alternative? Surely crashing is much worse. Could this be extracted into a macro?

**Comment by martanne** [comment]
> Envy works quite differently from vim so trying to make Vis behave like Envy will likely uncover lots of edge cases in the plugin API.

Yes this will likely be the case. Other necessary functionality might be missing entirely. Keep reporting issues as you encounter them, I should hopefully be able to spend some time on vis during the upcoming weeks.
